version: "3.9"
services:
  db:
    build: .dockerdb
    environment:
      - POSTGRES_PASSWORD=go-pipelines
      - POSTGRES_USER=go-pipelines
      - POSTGRES_DB=go-pipelines

  influx:
    image: influxdb:1.7

  grafana:
    image: grafana/grafana:4.1.0
    ports:
      - "9090:3000"
    depends_on:
      - influx

  go-pipelines:
    build: .
    ports:
      - "3333:3333"
    environment:
      - HTTP_PORT=3333
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=go-pipelines
      - DB_PASSWORD=go-pipelines
      - DB_NAME=go-pipelines
      - INFLUX_HOST=influx
      - INFLUX_PORT=8086
      - INFLUX_NAME=stats
      - INFLUX_USERNAME=go-pipelines
      - INFLUX_PASSWORD=go-pipelines
    depends_on:
      - db